[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
combine_as_imports = true

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203","W503","B950"]
# E203 conflita com black; W503 preferimos; B950 é recomendação estrita de linhas
per-file-ignores = [
  # Imports tardios em script CLI
  "code/load_swow.py:E402",
  # Exemplos/figuras com linhas longas:
  "NHB_Symbolic_Mainfold/code/analyze_swow.py:E501,B950",
  "NHB_Symbolic_Mainfold/code/integrate_entropy_curvature.py:E501",
  "NHB_Symbolic_Mainfold/code/compute_entropy_curvature_pro.py:E501",
  "NHB_Symbolic_Mainfold/scripts/utils.py:E501",
  "NHB_Symbolic_Mainfold/scripts/utils 2.py:E501",
]

[tool.autoflake]
remove-all-unused-imports = true
remove-unused-variables = true
in-place = true
