name: CI

on:
  push:
    branches: [ main, chore/**, feature/**, fix/** ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install pre-commit deps
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install-hooks

      - name: Run pre-commit (all files)
        run: pre-commit run --all-files

      - name: Build figures (idempotent)
        run: make figures

      - name: Build PDF with LaTeX (latexmk)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Manuscripts/Scientific_Reports_v1.6/Main_sr.tex
          # usa latexmk interno da action
          latexmk_use_lualatex: false
          # cache do texlive para acelerar builds
          extra_system_packages: "ghostscript gnuplot"
          pre_compile: |
            echo "[info] sync figures to manuscript dir"
            mkdir -p Manuscripts/Scientific_Reports_v1.6/figures
            rsync -a figs/ Manuscripts/Scientific_Reports_v1.6/figures/ || true
          post_compile: |
            echo "[ok] compile done"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Main_sr.pdf
          path: Manuscripts/Scientific_Reports_v1.6/Main_sr.pdf
          if-no-files-found: error
